[package]
name = "pit-c"
version = "0.2.4"
edition = "2021"
license = "CC0-1.0"
description = "Portal Interface Types Generator for C"

[dependencies]
hex = "0.4.3"
itertools = "0.13.0"
pit-core = { version = "0.2.0", path = "../pit-core" }
