[package]
name = "pit-rust-externref"
version = "0.2.5"
edition = "2021"
license = "CC0-1.0"
description = "Portal Interface Types"

[dependencies]
externref = { version = "0.2.0", features = ["processor"] }
