[workspace]
members=[ "pit-basic", "pit-c", "pit-cli","pit-core", "pit-patch", "pit-rust-externref", "pit-rust-generator", "pit-rust-guest", "pit-rust-host", "pit-rust-host-lib", "pit-teavm", "pit-wit-bridge", "tpit-rt"]
resolver="2"

[workspace.dependencies]
portal-pc-waffle = "0.3.2"
waffle-ast = "0.4"
