[package]
name = "pit-teavm"
version = "0.1.1"
edition = "2021"
license = "CC0-1.0"
description = "Portal Interface Types"

[dependencies]
hex = "0.4.3"
pit-core = { version = "0.1.0", path = "../pit-core" }
