[package]
name = "pit-teavm"
version = "0.4.0"
edition = "2021"
license = "CC0-1.0"
description = "Portal Interface Types for WebAssembly"

[dependencies]
hex = "0.4.3"
itertools = "0.13.0"
pit-core.workspace = true
